### ISSUE TITLE
Kobo Clara

### ISSUE THREAD

**Issue by juggernutscupper** [pgaskin/KoboStuff#1]
Hi,
Do you have the firmware for the new Kobo Clara?
I want to change the present fnac infected firmware with the pure original :-)
Thanks! KR Søren

**Comment by pgaskin** [comment]
Thanks for asking!

About the latest firmware, the situation regarding the download links right now is a bit complex (it has the same url as another version), so I'm waiting till the next version is released to add the Clara. If you really need it, I've uploaded it [here](https://transfer.sh/Oa4Gt/kobo-update-4.8.11090.zip).

For the FNAC advertising, you'll need to change the affiliate in .kobo/affiliate.conf. I suggest changing it to bestbuyca. The affiliate controls the FNAC branding and the speed of firmware updates. Nothing else is affected.

**Comment by juggernutscupper** [comment]
Thank you for the fast and informative answer!

As a matter of fact my main concern is to get the possibility to show the cover of the book I'm reading on the sleep screen.

This (fnac) firmware version (4.8.11090-bee5052c41 5/10/18) have removed the settings for choosing reading book cover as sleep screen. So I simply assume/hope that a non-fnac branded firmware will bring back these settings.

Do you know if this assumption is correct?

**Comment by pgaskin** [comment]
I'm not completely sure if the lack of the book cover setting is due to the firmware or the affiliate, but I think it is the affiliate. There's no harm in trying though, as it is quick to change.

You'll need to edit the `.kobo/affiliate.conf` file and change fnac to bestbuyca, then reboot.

**Comment by juggernutscupper** [comment]
Just found this: https://wiki.mobileread.com/wiki/Affiliate.conf - and it looks like it is a fnac specific setting.

I'll just have to figure out how to hack the Kobo and do as you suggest :-)

Thank you very much for the information and help!

**Comment by pgaskin** [comment]
No problem!

**Comment by NiLuJe** [comment]
Yup, just switch the affiliate (I think I went fnac - > kobo), reboot, and bam, proper settings :). I don't think I even had to update the firmware, there may have been a logout/login, but I got my H2O a while ago, so, err, my memory is a bit fuzzy...
