### ISSUE TITLE
Issue with Kobo firmware update

### ISSUE THREAD

**Issue by shad0wspan** [pgaskin/KoboStuff#10]
Kobo   Aura H2O | kobo5 | 4.18.13737

Reading progress does not update unless book is re-opened from My books or Home screen

Previous update 14.17.13694 worked perfectly.

**Comment by pgaskin** [comment]
Yes, this has been mentioned in the threads on MobileRead. You'll need to report it to Kobo on their website, or discuss it in those threads if you want.
