### ISSUE TITLE
Nouvezu firmware Kobo

### ISSUE THREAD

**Issue by hpfou** [pgaskin/KoboStuff#11]
Bonjour, je viens de télécharger la version 4.20.14601 sur ma Kobo Aura H2O, et la fonction série ne semble pas fonctionner correctement. Mes livres sont sur carte micro SD.
merci de votre aide

**Comment by pgaskin** [comment]
You need to download and run the newest version of [seriesmeta](https://github.com/geek1011/kepubify/releases/latest) (part of kepubify) to be able to use the series tab with sideloaded books.
