### ISSUE TITLE
Kobo Vox request

### ISSUE THREAD

**Issue by kitty797** [pgaskin/KoboStuff#13]
Any idea what firmware I need for a Kobo Vox?  I've turned mine off after a (very) long time, and would love to update it.

**Comment by pgaskin** [comment]
The Kobo Vox is not really in scope here. It's more of an Android Tablet than an eReader, and I mainly focus on eReader stuff. You might have better luck asking on MobileRead, but AFAIK, if you haven't updated to the latest firmware yet, it's not possible anymore.
