### ISSUE TITLE
Feature wish....Dictionary

### ISSUE THREAD

**Issue by ricvader** [pgaskin/KoboStuff#14]
Hi, i love my Kobo Glo HD, new updates is great.

I wish there's an official English - Chinese dictionary made available. that will be a great help.

Another thing is when Wifi is connected, it always showing 1 bar or no bar at all. is this normal? even after i sync it, or use the browser. it never show more than 1 bar, even when i am next to wifi router.

thanks alot for your hard work.

**Comment by pgaskin** [comment]
The WiFi issue has been around for a while. The bars aren't representative of the real signal strength, so you can safely ignore them.

I can't do anything about new official dictionaries. You should request it on the Kobo website through the feedback form.
