### ISSUE TITLE
new Kobo firmware 4.24 prevents linking to PC and Mac

### ISSUE THREAD

**Issue by wilbertb1** [pgaskin/KoboStuff#15]
Not sure this is the right forum, but I will try.
A colleague with a Kobo Glo HD could no longer connect her Kobo to her Mac after the firmware updated to version 4.24.15676
It was not a problem of cable or her Mac, as my older Kobo Glo could easily connect with her Mac. Wifi connections to Kobo bookshop still work. Her Kobo Glo HD could also not connect to my Windows 10 PC, whereas my Kobo with older firmware could. After upgrading my Kobo Glo to the Sept 2020 4.24.15676 I had the same problem of not being able to connect. So this is proof that the new 4.24 firmware has a bug preventing cacble connections.
Suggestions how to inform the Kobo software builders? Or alternatively, how to do a firmware downgrade via Wifi? I want to avoid a reset as I then lose many ebooks. Thanks for your support. wilbertb1

**Comment by pgaskin** [comment]
You should contact Kobo via the general feedback option for the chat on the Kobo website (you'll need to disable your adblocker to see it if you have one).

**Comment by wilbertb1** [comment]
OK, thanks for the advice! Your listing of the firmwares was actually very helpful, and came up higher in Google than Kobo help…

I have now sent the question to the Kobo developers. Curious what they will come up with…

 �

Wilbert

 �
