### ISSUE TITLE
Removing recommended online books

### ISSUE THREAD

**Issue by unknown321** [pgaskin/KoboStuff#2]
I had a selection of online-only books on my KoboH2O. There was no way to remove them from the list of my books (probably because of skipped registration), I could only mark them as 'not interested'.

You can remove them like this from `.kobo/KoboReader.sqlite`:

`delete from content where ContentID not like '%onboard%';`

**Comment by pgaskin** [comment]
That seems to work. The only thing you might want to change is the `%onboard%`, because that would make it remove books stored on an external SD card. It should work if you use `%mnt%`.

**Comment by unknown321** [comment]
Depends on device, I don't have sd card so it did exactly what I wanted without any issues. Anyway, I think this should be in the tips.

**Comment by pgaskin** [comment]
Yep. I haven't updated the tips recently, but once I get around to it, I'll add your tip. Thanks!
