### ISSUE TITLE
Hello, can you provide the SD card image of KOBO GLO?

### ISSUE THREAD

**Issue by H-Wenfeng** [pgaskin/KoboStuff#20]
I lost my backup for internal SD card, can you help me ?

**Comment by H-Wenfeng** [comment]
I try to use N905C's image instead, and it works.

**Comment by H-Wenfeng** [comment]
I find that the screen resolution is wrong, it doesn't work good......

**Comment by pgaskin** [comment]
You need to ask @davidfor on the MobileRead Forums for SD card images.
