### ISSUE TITLE
Kobo Glo HD on 4.28.18220

### ISSUE THREAD

**Issue by ricvader** [pgaskin/KoboStuff#23]
After updated to 4.28.18220, my Kobo Glo HD sometimes freezes and have to wait for a long while to turn a page, wake from sleep, or go back to home page.
it can take up to 15 sec for a respond. it's not all the time, but it happens quite frequently.

**Comment by pgaskin** [comment]
This page doesn't have anything to do with Kobo. Try asking on MobileRead (an unofficial discussion forum), or if you have more details, contacting Kobo.
