### ISSUE TITLE
Automatic turn off to 6 o 12h ?

### ISSUE THREAD

**Issue by FranckRICHARD01** [pgaskin/KoboStuff#30]
Hello and thank you for your excellent work.
To increase the battery life, I personally prefer the Sage to turn off completely after a certain time. 
But the button to turn on the Sage is a bit difficult to access behind the magnetic case, so I don't really like having to remove it each time when it is fully turned off.    
However, the maximum delay for the automatic power off is 1 hour maximum, which seems to me too little. Would it be possible to extend this maximum delay and propose 6h or 12h?

Thank you!

**Comment by pgaskin** [comment]
There is already a [patch](https://pgaskin.net/kobopatch-patches/lgrpwroff-14601.html) for this, although it does seem to be somewhat buggy in certain cases.
