### ISSUE TITLE
Versions of firmware

### ISSUE THREAD

**Issue by hpfou** [pgaskin/KoboStuff#32]
Hello,
the dates of new versions are not correct. The last version was, for Libra 2 : 4.35.20400.
Thank you for correction
Bye

**Comment by pgaskin** [comment]
https://github.com/pgaskin/KoboStuff/commit/4f55f97b8e004b957d56de94cb2641ef8bc0419b#commitcomment-93274907

**Comment by wegotourselvesareader** [comment]
Heh. I came here to report this as well. Ditto on my Clara HD.

Curiously, my new Clara 2E, with the same Affiliate entry of "Kobo" as the Clara HD, does not pick up the 4.35.20400 update.
