### ISSUE TITLE
New firmware version 4.38 has been released

### ISSUE THREAD

**Issue by ndtoan96** [pgaskin/KoboStuff#38]
I notice that the new version 4.38.21908 (released on August 22, 2023) is not updated on https://pgaskin.net/KoboStuff/kobofirmware.html

How do you get the firmware? Maybe I can help.

**Comment by zarelit** [comment]
According to this article https://blog.the-ebook-reader.com/2023/08/31/new-kobo-software-update-fails-to-fix-pocket-login-issues/ the update has issues and it has been pulled so the latest one for users is still the one released in July

**Comment by pgaskin** [comment]
I know; I was away when the firmware was released, and haven't got around to adding the firmware to the old versions list, and it was pulled, so it isn't current visible on the page, even with the other versions button.

**Comment by pgaskin** [comment]
Done.
