### ISSUE TITLE
Links in kfw.db.js for firmware 4.38.21908 partially not working

### ISSUE THREAD

**Issue by folkemat** [pgaskin/KoboStuff#39]
Hello,
while using KoboPatchFan, I noticed that the firmware 4.38.21908 for the Clara 2E and the Elipsa 2E is not available on the CDN akamaihd.net referenced in kfw.db.js. 

The two lines:
```
[dh+"10",dd+"386","4.38.21908","August 2023",da+"10Augl2023/kobo-update-4.38.21908.zip"],
[dh+"11",dd+"389","4.38.21908","August 2023",da+"11Augl2023/kobo-update-4.38.21908.zip"],
```
which should give 
```
https://kbdownload1-a.akamaihd.net/firmwares/kobo10Augl2023/kobo-update-4.38.21908.zip 
https://kbdownload1-a.akamaihd.net/firmwares/kobo11Augl2023/kobo-update-4.38.21908.zip 
```
do not work.

For all other Kobos, however, the referenced links in kfw.db.js for firmware 4.38.21908 seem to work.  

Edit:
I've just realised that it's just a small error in the format: it should be 10/Aug2023/kobo-update-4.38.21908.zip and not 10Augl2023/kobo-update-4.38.21908.zip!

**Comment by pgaskin** [comment]
Fixed.
