### ISSUE TITLE
ACTUALIZACION KOBO MINI

### ISSUE THREAD

**Issue by CHENANO14** [pgaskin/KoboStuff#47]
Tengo bloqueado el KOBO MINi del año 2012. NO encuentro firmware para actualizarlo.

**Comment by pgaskin** [comment]
Debe descargar y instalar manualmente el firmware 3.19.5761 o posterior.

https://cdn.kobo.com/downloads/firmwares/kobo4/january2016/kobo-update-3.19.5761-s.zip

**Comment by CHENANO14** [comment]
Muy Buenos días y muchas gracias.

Saludos Cordiales

Javier García

De: Patrick Gaskin ***@***.***>
Enviado el: martes, 28 de noviembre de 2023 6:56
Para: pgaskin/KoboStuff ***@***.***>
CC: CHENANO14 ***@***.***>; Author ***@***.***>
Asunto: Re: [pgaskin/KoboStuff] ACTUALIZACION KOBO MINI (Issue #47)


Debe descargar y instalar manualmente el firmware 3.19.5761 o posterior.

https://cdn.kobo.com/downloads/firmwares/kobo4/january2016/kobo-update-3.19.5761-s.zip

-
