### ISSUE TITLE
Help Libra Colour

### ISSUE THREAD

**Issue by kentpuait** [pgaskin/KoboStuff#50]
Good afternoon.
I ask for help, accidentally installed firmware (5- versions) on Libra Color which was intended for Clara Color, I did not see what was for Clara, the topic was for libra, now some of the functions do not work, I don’t know how to return back, for the firmware (there was 4 -I)? I tried to reflash several times, nothing happens.

**Comment by pgaskin** [comment]
I don't entirely understand what you are asking. Which version were you on, and exactly which update package, and from where, did you install?

And what's a "raznet" and "threw firmware files"?

**Comment by pgaskin** [comment]
I saw your posts on MobileRead. It is not possible to revert (without doing a bunch of unsupported stuff manually) after installing the tolino 4->5 update package without a full image.

There is a reason why I haven't linked that package on the firmware page yet...

**Comment by kentpuait** [comment]
Could you tell me where I can download the image for libra and installation instructions, if available of course?

**Comment by pgaskin** [comment]
Nobody's taken an image yet AFAIK, and even if they had, installation isn't straightforward as you currently only really get one attempt at the critical steps.

If you do end up finding an image, don't just write it blindly; you'll want to write the partitions in stages such that the default boot partition always works.

**Comment by kentpuait** [comment]
It turns out you need to wait for the release of the new native firmware of the 5th version and only then try to flash? If he comes out of course in the near future.

**Comment by pgaskin** [comment]
Yes, that would also work, but not the initial conversion update (at least without modification).

BTW, if you don't already know, I'm geek1011 on MobileRead.
